language: node_js
node_js:
  - "8.11"
cache:
  yarn: true
  directories:
    - "node_modules"
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
